[MinecraftServerConfig]
  PathToMcServers = "../mcservers/"
  MaxAllowedRam = "1024M"
  MinAllowedRam = "1024M"
  ServerJarName = "server.jar"
  OthersCommandArguments = "nogui"

[WebAppConfig]
  Port = "8082"
